### ISSUE TITLE
Error after upgrading ts-jose to version 5.2.2 

### ISSUE THREAD

**Issue by mira-ayman95** [evan361425/ts-jose#120]
When attempting to build my project, an error while upgrade ts-jose to 5.2.2 

the following error appeared :- 
``` 
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Path\node_modules\ts-jose\dist\cjs\index.js from C:Path/file.ts not supported.
index.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.

Instead rename index.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in C:\Path\node_modules\ts-jose\package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead). 
```
Steps to reproduce:

npm install ts-jose@5.2.2
npm start
Observe the error message for 'ts-jose'

Expected behavior:
should build successfully without any errors.

Actual behavior:
The build failed

Environment:

Node version: v18.16.0
Typescript version: 4.9.5
Possible solution:
Update the package.json  from
```
  "type": "module",  //to "type": "commonjs",
```
 as suggested in the error message.

**Comment by evan361425** [comment]
It seems like there's an export type error. I'll investigate shortly.

**Comment by evan361425** [comment]
I have resolved the common JS issue by renaming the compiled file, which was tricky because TypeScript lacks native support for transforming file extensions.

I'm trying to avoid using `webpack` or other similar packages to minimize complexity in this small project.

**Comment by mira-ayman95** [comment]
@evan361425 works fine,
Thank you.
