### ISSUE TITLE
package.json exports should have types entry I guss..

### ISSUE THREAD

**Issue by user3232** [evan361425/ts-jose#126]
When importing 'ts-jose' package, types does not work in VS Code.

```ts
import {} from 'ts-jose'

```

Typescript shows error on hover:

> Could not find a declaration file for module 'ts-jose'. '/home/mk/github/lib/auth/node_modules/ts-jose/dist/mjs/index.js' implicitly has an 'any' type.
>  There are types at '/home/mk/github/lib/auth/node_modules/ts-jose/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'ts-jose' library may need to update its package.json or typings.ts(7016)

Updating `package.json` with:

```json
{
  "exports": {
    "types": "./dist/index.d.ts",
    "import": "./dist/mjs/index.js",
    "require": "./dist/cjs/index.cjs"
  }
}
```
solves the problem.

**Comment by evan361425** [comment]
fixed in the commit as above shown but the new package only update after new `jose` release

If you need a new bump to use, tell me.
