### ISSUE TITLE
Error building typescript in 'ts-jose' missing declaration files Version 4.14.0 

### ISSUE THREAD

**Issue by mira-ayman95** [evan361425/ts-jose#70]
When attempting to build my project, an error occurred due to missing declaration files for the 'ts-jose' module. The error message suggests installing '@types/ts-jose' or adding a new declaration file. The issue seems to have been caused by the release of ts-jose 4.14.0 on 2023-04-17.

Steps to reproduce:

npm install ts-jose@4.14.0
npm start
Observe the error message regarding missing declaration files for 'ts-jose'

Expected behavior:
should build successfully without any errors.

Actual behavior:
The build failed due to missing declaration files for 'ts-jose'.

Environment:

Node version: v14.20.0
Typescript version: 4.6.3
Possible solution:
Update the code to include the declaration files for 'ts-jose' or install '@types/ts-jose' as suggested in the error message.

Additional context:
The issue seems to have been caused by the release of ts-jose 4.14.0 on 2023-04-17.

**Comment by evan361425** [comment]
I will take a look soon, thanks a lot for reporting.

**Comment by evan361425** [comment]
Sorry for the inconvenient! I have miss the declaration setting in `tsconfig.json`.

You can see the fix in https://github.com/evan361425/ts-jose/commit/66b996098b37041a9a684af57f0f07b41e9fd489

It has released in [v4.14.1](https://github.com/evan361425/ts-jose/releases/tag/v4.14.1).

**Comment by mira-ayman95** [comment]
@evan361425 Thank you, it works fine now.
